"""operator: add name, role, email, remove phone_number; order, remove number_or_people

Revision ID: 596cef1383bf
Revises: 497bab98165d
Create Date: 2024-04-23 20:59:03.693448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '596cef1383bf'
down_revision: Union[str, None] = '497bab98165d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('operators', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.add_column('operators', sa.Column('role', sa.String(length=255), nullable=True))
    op.drop_column('operators', 'phone_number')
    op.drop_column('orders', 'number_of_people')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('number_of_people', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('operators', sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('operators', 'role')
    op.drop_column('operators', 'email')
    op.drop_column('operators', 'name')
    # ### end Alembic commands ###
