"""order: operator_id may be nullable

Revision ID: d7e26455944c
Revises: 596cef1383bf
Create Date: 2024-04-25 18:30:42.510500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e26455944c'
down_revision: Union[str, None] = '596cef1383bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
