"""user: rename chat_id to customer_id

Revision ID: e27c735dcf4c
Revises: c3ace07b7c4e
Create Date: 2024-04-26 02:29:27.520284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27c735dcf4c'
down_revision: Union[str, None] = 'c3ace07b7c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_id', sa.String(length=255), nullable=True))
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'customer_id')
    # ### end Alembic commands ###
