"""order: remove duplicate note; note may be nullable

Revision ID: ef54f7702a5b
Revises: 0c135a3feb53
Create Date: 2024-05-02 11:54:15.394165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef54f7702a5b'
down_revision: Union[str, None] = '0c135a3feb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
