"""lexicon model

Revision ID: f061411abcef
Revises: 2c8407eeee88
Create Date: 2024-05-09 23:24:08.816868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f061411abcef'
down_revision: Union[str, None] = '2c8407eeee88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexicon',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lexicon')
    # ### end Alembic commands ###
