"""order: some fields shouldn't be nullable

Revision ID: fd09fc90e5a7
Revises: d7e26455944c
Create Date: 2024-04-25 18:34:29.992600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd09fc90e5a7'
down_revision: Union[str, None] = 'd7e26455944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'start_address',
               existing_type=sa.CHAR(length=256),
               nullable=False)
    op.alter_column('orders', 'destination_address',
               existing_type=sa.CHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'destination_address',
               existing_type=sa.CHAR(length=256),
               nullable=True)
    op.alter_column('orders', 'start_address',
               existing_type=sa.CHAR(length=256),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
